name: test suite
on:
  push:
    branches-ignore:
        - "gh-readonly-queue/**"
  pull_request:
  merge_group:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master # avoid the tack to prevent dependabot updates
        with:
          toolchain: "1.86"
      - run: cargo test --all-targets --all-features
      - run: cargo test --doc --all-features

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master # avoid the tack to prevent dependabot updates
        with:
          toolchain: "1.86"
          components: rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master # avoid the tack to prevent dependabot updates
        with:
          toolchain: "1.86"
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo clippy --all-targets --features=nusb -- -D warnings
      - run: cargo clippy --all-targets --features=libusb -- -D warnings
      - run: cargo clippy --all-targets --features=async -- -D warnings

  allgreen:
    if: always()
    needs:
    - test
    - fmt
    - clippy
    runs-on: Ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
